INSERT INTO amazbd.produto (produto.id, produto.visivel , produto.titulo, produto.descricao, produto.link_foto, produto.preco, produto.qtd_estoque, produto.categoria_id)
VALUES
(null, 1, "Boneca em tecido fruta (guaraná) da Amazônia", 
		"A Boneca em Tecido Fruta feita pelo grupo produtivo Manaus Feito à Mão, traz a representatividade cultural e econômica do Guaraná para os povos caboclos. O produto foi confeccionado com o talento e criatividade da artesã Lilian Oliveira, usando de fibras vegetais, sementes, frutas e grafismos indígenas.", 
		"https://images-americanas.b2w.io/produtos/01/00/img/102718/1/102718162_1GG.jpg",
        135.00,
        4,
        7),
(null, 1, "Cesto em fibra Japim vermelho com acabamento da Amazônia",
	   "A maior expressividade do Vaso em Fibra Japiim Solta Vermelho com Acabamento da Amazônia é a técnica usada e as emoções que envolvem a arte 100% artesanal. Uma peça que se adapta em vários ambientes, com a bagagem e design cultural do Amazonas.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1371133/8/1371133822_1GG.jpg",
       409.00,
       6,
	   1),
(null, 1, "Café Apuí agroflorestal da Amazônia extra forte",
	   "O Café Orgânico Apuí Agroflorestal Extra Forte da Amazônia é oriundo do munícipio de Apuí no sul do Amazonas. Ele é o primeiro café do estado a atingir a certificação orgânica e busca resgatar o potencial local de produção cafeeira de forma sustentável. É Com sabor inesquecível, não utiliza agrotóxicos em sua composição e é encorpado com grãos de alta qualidade.",
       "https://images-americanas.b2w.io/produtos/01/00/img/470268/3/470268360_1GG.jpg",
       19.90,
       325,
	   3),
(null, 1, "Embalagem para presente de fibra de Cauaçu tingido com folhas de Crajiru da Amazônia - Modelo X",
	   "Formada por artesãs da Comunidade São João de Ipecaçu, São Paulo, Vila Nova e Nova Canaã a marca Teçume D’Amazônia se dedica a confeccionar cestas a partir das fibras de cauaçu, uma erva que pode atingir até 5 metros de altura. Trabalho artesanal que promoveu uma nova relação entre as artesãs e o cauaçu, já que antes a erva era usada somente nos telhados das cozinhas e nos fornos de farinha das comunidades da Reserva de Desenvolvimento Sustentável do Amanã, na região do médio Solimões. Hoje, viram produtos sustentáveis que, além de contribuírem para um mundo melhor, garantem a preservação da cultura.",
       "https://images-americanas.b2w.io/produtos/01/00/img/80621/2/80621231_1GG.jpg",
       29.90,
       14,
	   13),
(null, 1, "Bolsa colorida em sementes de Açaí e Morototó da Amazônia",
	   "A Bolsa Colorida de Sementes de Açaí e Morototó da Amazônia, é uma opção prática para guardar os seus pertences. Produzida 100% manualmente, é muito útil para o dia a dia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1370389/1/1370389199_1GG.jpg",
       79.90,
       21,
	   14),
(null, 1, "Garrafa de mesa de fibra de Cauaçu tingido com folhas de Crajiru e Açafrão da Amazônia",
	   "Formada por artesãs das comunidades São João de Ipecaçu, São Paulo, Vila Nova e Nova Canaã a marca Teçume D’Amazônia se dedica a confeccionar cestas a partir das fibras de cauaçu, uma erva que pode atingir até 5 metros de altura. Trabalho artesanal que promoveu uma nova relação entre as artesãs e o cauaçu, já que antes a erva era usada somente nos telhados das cozinhas e nos fornos de farinha das comunidades da Reserva de Desenvolvimento Sustentável do Amanã, na região do médio Solimões. Hoje, viram produtos sustentáveis que, além de contribuírem para um mundo melhor, garantem a preservação da cultura.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1389566/0/1389566052_1GG.jpg",
       76.14,
       9,
	   13),
(null, 1, "Bandeja em resíduo de madeira marchetada Home Bar - Projeto Design Tropical da Amazônia",
	   "Sabemos que uma bandeja, quando bem posta, pode redesenhar todo um ambiente. A pintura vermelha se destaca na madeira Guaraná, que carrega uma bagagem de cultura, criatividade e elegância para sua casa.",
       "https://images-americanas.b2w.io/produtos/01/00/img/75390/2/75390243_1GG.jpg",
       550.00,
       3,
	   13),
(null, 1, "Boneco índio da amazônia.",
	   "Boneco índio da amazônia em tecido feito artesanalmente.",
       "https://images-americanas.b2w.io/produtos/01/00/img/102718/0/102718083_1SZ.jpg",
       70.00,
       5,
	   13),
(null, 1, "Fruteira de mesa de folha.",
	   "Fruteira de mesa de folha do wambé da amazônia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1370322/7/1370322761_1GG.jpg",
       369.00,
       8,
	   13),
(null, 1, "Bolsa colorida com alça em sementes de açaí.",
	   "Bolsa colorida com alça em sementes de açaí da amazônia e morototó tingido.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1370389/3/1370389391_1GG.jpg",
       79.90,
       4,
	   14),
(null, 1, "Café apuí agroflorestal da amazônia orgânico",
	   "Café apuí agroflorestal da amazônia orgânico.",
       "https://images-americanas.b2w.io/produtos/01/00/img/470269/0/470269039_1GG.jpg",
       29.90,
       31,
	   3),
(null, 1, "Vaso coringa.",
	   "Vaso coringa da amazônia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1371128/6/1371128661_1GG.jpg",
       429.00,
       4,
	   13),
(null, 1, "Boneca em tecido fruta (Tucumã)",
	   "boneca em tecido fruta (Tucumã) da amazônia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/102720/1/102720171_1GG.jpg",
       135.00,
       4,
	  7),
(null, 1, "Vaso em fibra maracujá.",
	   "Vaso em fibra maracujá vermelho da Amazônia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1389722/9/1389722991_1GG.jpg",
       429.00,
       3,
	   13),
(null, 1, "Conjunto de colares.",
	   "Conjunto de colares em madeira e sementes da Amazônia",
       "https://images-americanas.b2w.io/produtos/01/00/img/1370402/6/1370402630_1GG.jpg",
       99.50,
       12,
	   14);
