INSERT INTO amazbd.usuario (usuario.idUsuario, usuario.nome, usuario.telefone, usuario.email, usuario.senha)
VALUES
(null, "João Carlos Eduardo Sebastião", 84985960857, "josecarlose@gmail.com", "7J4okqDLjP" ),
(null, "Renato Henrique da Paz", 84998818251, "renatohenriquedapaz_@humanfit.com.br", "hHRYrWcsWO" ),
(null, "César Marcos Cardoso", 84987262264, "cesarmarcoscardoso@tedde.com.br", "um9uzbhztb" ),
(null, "Geraldo Levi Monteiro", 84982119888, "geraldolevimonteiro-94@creativeinteriores.com.br", "nlzKmg932P" ),
(null, "Nathan Martin da Rocha", 84994030232, "renatohenriquedapaz_@humanfit.com.br", "4G2Thf1GOY" ),
(null, "Lucca da Silva Gregorio", 84981306395, "luccadasilvagregorio_@pharmaterra.com.br", "IknotOxR1O" ),
(null, "Augusto Arthur Gustavo Gonçalves", 84981666941, "augustoarthurgustavo-85@cavalinho.srv.br", "zoCwL8ZD3k" ),
(null, "Manoel Ian Ferreira", 84998215967, "mmanoelianferreira@bitco.cc", "FCkrDJeKU6" ),
(null, "Luiza da Silva Gregorio", 84994030232, "luizagregorio@humanfit.com.br", "4G2Thf1GOY" ),
(null, "Theo Levi Enzo da Cruz", 84981590939, "ttheolevienzodacruz@kantoferramentaria.com.br", "HY2aOoc7qo" ),
(null, "Francisco Bernardo Alexandre Sales", 84994421805, "alexandresales-89@publifix.com.br", "JoMmWCLm1w" ),
(null, "Jorge Elias das Neves", 84988840320, "jorgeeliasdasneves@opusvp.com.br", "rEQxsZ0x7G" ),
(null, "Pedro Henrique Kauê Nicolas Porto", 84986542388, "pedrohenrique@pharmaterra.com.br", "TfZmJwCl73" ),
(null, "Noah Ricardo da Costa", 84997573565, "noahricardodacosta_@pp33.com.br", "OetnL2oPnq" ),
(null, "Liz Gregorio", 11977542152, "liz@gmail.com", "123456789@@" );

INSERT INTO amazbd.venda (venda.idVenda, venda.dataVenda, venda.idUsuario)
VALUES
(null, '2017-05-05' , 1 ),
(null, '2017-01-09' , 2 ),
(null, '2017-05-16' , 3 ),
(null, '2017-07-20' , 4 ),
(null, '2017-08-22' , 5 ),
(null, '2018-01-09' , 6 ),
(null, '2018-02-02' , 7 ),
(null, '2018-05-16' , 8 ),
(null, '2018-09-17' , 9 ),
(null, '2018-10-22' , 10 ),
(null, '2018-12-29' , 11 ),
(null, '2019-01-05' , 12 ),
(null, '2019-09-19' , 13 ),
(null, '2019-12-18' , 14 ),
(null, '2019-12-30' , 15 );

INSERT INTO amazbd.categoria (categoria.idCategoria, categoria.nome, categoria.descricao)
VALUES
(null, "Balde", "Recipiente com alça, feito de metal, plástico ou madeira"),
(null, "Colar", "ornato que se usa no pescoço."),
(null, "Alimentos", "Produtos alimenticios."),
(null, "Jarro", "Vaso para decoração ou para conter flores"),
(null, "Quadro", "Moldura, caixilho de madeira ou outro material."),
(null, "Chinelo", "Calçado macio e confortável, com ou sem salto."),
(null, "Boneca", "Representação tridimensional de um corpo humano feminino, infantil ou adulto, feita de pano, porcelana, borracha etc."),
(null, "Copo", "O copo é um recipiente feito de vidro, plástico e outros materiais, de formato cilíndrico."),
(null, "Chocalho", "Espécie de sineta em forma de cone ou cilindro achatado que se prende ao pescoço do gado ou das bestas de carga e que, agitado pelo movimento do animal, produz um som baço, metálico, monótono"),
(null, "Instrumento", "Um instrumento musical é um objeto construído com o propósito de produzir música."),
(null, "Tapete", "revestimento feito de outro material (borracha, linóleo etc.)"),
(null, "Bracelete", "Um bracelete é uma peça de joalheria ou bijuteria que serve para adornar o pulso das mãos de um indivíduo."),
(null, "Decoração", "conjunto de elementos de uma obra de arte ou peça artística que apelam aos sentidos (cor) ou despertam sensações (forma e movimento)."),
(null, "Vestimenta", "peça de roupa que serve para vestir qualquer parte do corpo."),
(null, "Mascaras", "DescriçãoUma máscara é um acessório utilizado para cobrir o rosto. É utilizada para diversos propósitos: lúdicos, religiosos, artísticos ou de natureza prática. ");

INSERT INTO amazbd.produto (produto.idProduto, produto.titulo, produto.descricao, produto.linkFoto, produto.preco, produto.qtdEstoque, produto.idCategoria)
VALUES
(null, "Boneca Em Tecido Fruta (guaraná) Da Amazônia", 
		"A Boneca em Tecido Fruta feita pelo grupo produtivo Manaus Feito à Mão, traz a representatividade cultural e econômica do Guaraná para os povos caboclos. O produto foi confeccionado com o talento e criatividade da artesã Lilian Oliveira, usando de fibras vegetais, sementes, frutas e grafismos indígenas.", 
		"https://images-americanas.b2w.io/produtos/01/00/img/102718/1/102718162_1GG.jpg",
        135.00,
        4,
        7),
(null, "Cesto Em Fibra Japiim Vermelho Com Acabamento Da Amazônia",
	   "A maior expressividade do Vaso em Fibra Japiim Solta Vermelho com Acabamento da Amazônia é a técnica usada e as emoções que envolvem a arte 100% artesanal. Uma peça que se adapta em vários ambientes, com a bagagem e design cultural do Amazonas.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1371133/8/1371133822_1GG.jpg",
       409.00,
       6,
	   1),
(null, "Café Apuí Agroflorestal Da Amazônia Extra Forte",
	   "O Café Orgânico Apuí Agroflorestal Extra Forte da Amazônia é oriundo do munícipio de Apuí no sul do Amazonas. Ele é o primeiro café do estado a atingir a certificação orgânica e busca resgatar o potencial local de produção cafeeira de forma sustentável. É Com sabor inesquecível, não utiliza agrotóxicos em sua composição e é encorpado com grãos de alta qualidade.",
       "https://images-americanas.b2w.io/produtos/01/00/img/470268/3/470268360_1GG.jpg",
       19.90,
       325,
	   3),
(null, "Embalagem Para Presente De Fibra De Cauaçu Tingido Com Folhas De Crajiru Da Amazônia - Modelo X",
	   "Formada por artesãs da Comunidade São João de Ipecaçu, São Paulo, Vila Nova e Nova Canaã a marca Teçume D’Amazônia se dedica a confeccionar cestas a partir das fibras de cauaçu, uma erva que pode atingir até 5 metros de altura. Trabalho artesanal que promoveu uma nova relação entre as artesãs e o cauaçu, já que antes a erva era usada somente nos telhados das cozinhas e nos fornos de farinha das comunidades da Reserva de Desenvolvimento Sustentável do Amanã, na região do médio Solimões. Hoje, viram produtos sustentáveis que, além de contribuírem para um mundo melhor, garantem a preservação da cultura.",
       "https://images-americanas.b2w.io/produtos/01/00/img/80621/2/80621231_1GG.jpg",
       29.90,
       14,
	   13),
(null, "Bolsa Colorida Em Sementes De Açaí E Morototó Da Amazônia",
	   "A Bolsa Colorida de Sementes de Açaí e Morototó da Amazônia, é uma opção prática para guardar os seus pertences. Produzida 100% manualmente, é muito útil para o dia a dia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1370389/1/1370389199_1GG.jpg",
       79.90,
       21,
	   14),
(null, "Garrafa De Mesa De Fibra De Cauaçu Tingido Com Folhas De Crajiru E Açafrão Da Amazônia",
	   "Formada por artesãs das comunidades São João de Ipecaçu, São Paulo, Vila Nova e Nova Canaã a marca Teçume D’Amazônia se dedica a confeccionar cestas a partir das fibras de cauaçu, uma erva que pode atingir até 5 metros de altura. Trabalho artesanal que promoveu uma nova relação entre as artesãs e o cauaçu, já que antes a erva era usada somente nos telhados das cozinhas e nos fornos de farinha das comunidades da Reserva de Desenvolvimento Sustentável do Amanã, na região do médio Solimões. Hoje, viram produtos sustentáveis que, além de contribuírem para um mundo melhor, garantem a preservação da cultura.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1389566/0/1389566052_1GG.jpg",
       76.14,
       9,
	   13),
(null, "Bandeja em Resíduo de Madeira Marchetada Home Bar - Projeto Design Tropical da Amazônia",
	   "Sabemos que uma bandeja, quando bem posta, pode redesenhar todo um ambiente. A pintura vermelha se destaca na madeira Guaraná, que carrega uma bagagem de cultura, criatividade e elegância para sua casa.",
       "https://images-americanas.b2w.io/produtos/01/00/img/75390/2/75390243_1GG.jpg",
       550.00,
       3,
	   13),
(null, "Boneco índio da amazônia.",
	   "Boneco índio da amazônia em tecido feito artesanalmente.",
       "https://images-americanas.b2w.io/produtos/01/00/img/102718/0/102718083_1SZ.jpg",
       70.00,
       5,
	   13),
(null, "Fruteira de mesa de folha.",
	   "Fruteira de mesa de folha do wambé da amazônia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1370322/7/1370322761_1GG.jpg",
       369.00,
       8,
	   13),
(null, "Bolsa colorida com alça em sementes de açaí.",
	   "Bolsa colorida com alça em sementes de açaí da amazônia e morototó tingido.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1370389/3/1370389391_1GG.jpg",
       79.90,
       4,
	   14),
(null, "Café apuí agroflorestal da amazônia orgânico",
	   "Café apuí agroflorestal da amazônia orgânico.",
       "https://images-americanas.b2w.io/produtos/01/00/img/470269/0/470269039_1GG.jpg",
       29.90,
       31,
	   3),
(null, "Vaso coringa.",
	   "Vaso coringa da amazônia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1371128/6/1371128661_1GG.jpg",
       429.00,
       4,
	   13),
(null, "Boneca em tecido fruta (Tucumã)",
	   "boneca em tecido fruta (Tucumã) da amazônia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/102720/1/102720171_1GG.jpg",
       135.00,
       4,
	  7),
(null, "Vaso em fibra maracujá.",
	   "Vaso em fibra maracujá vermelho da Amazônia.",
       "https://images-americanas.b2w.io/produtos/01/00/img/1389722/9/1389722991_1GG.jpg",
       429.00,
       3,
	   13),
(null, "Conjunto de colares.",
	   "Conjunto de colares em madeira e sementes da Amazônia",
       "https://images-americanas.b2w.io/produtos/01/00/img/1370402/6/1370402630_1GG.jpg",
       99.50,
       12,
	   14);

INSERT INTO amazbd.pedido (pedido.idPedido,  pedido.qtdProduto, pedido.valorPago, pedido.idVenda, pedido.idProduto)
VALUES
(null, 1, 135.00, 1, 1),
(null, 1, 409.00, 2, 2),
(null, 1, 19.90, 3, 3),
(null, 1, 29.90, 4, 4),
(null, 1, 79.90, 5, 5),
(null, 1, 76.14, 6, 6),
(null, 2, 1100.00, 7, 7),
(null, 2, 140.00, 8, 8),
(null, 3, 1107.00, 9, 9),
(null, 1, 79.90, 10, 10),
(null, 1, 29.90, 11, 11),
(null, 2, 858.00, 12, 12),
(null, 3, 405.00, 13, 13),
(null, 1, 429.00, 14, 14),
(null, 5, 497.50, 15, 15);




